---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCYYwC5w6sA94RC22/sDXxTkJBldtM0/WtPkifE9DO5Hb5TF4c//r+/BG3CRQTNKL0hzO4yf+LfMlPtHLnArUjcdWzLgZ/yqlLmlUMeEFSKq3vZZC65X0JBHOEnDIP5NtkNwJGIe9nYjjhl5xtYHH8dDqkA+uvicTm/aerVhrwfViRmjl2XAmY0j2cukykuFVVtmvUZO5MJmku1IAvUAS8KfpYPDc1IJ5/UyeXh40vgqEc0a5frQET9sCJicrBpQ+x93skYR98KANpgFctOH1VZQMDgNntdHAd2L/i6aFZ1fI6KHGCJL0x4hqbvdu3yN/vVINpnlMvhQp4qcTu27Kq0zZncwyz7R+YACVIFwP4/R51eZNllmwNylyos3HfDzoriSuiDXoohgcxqFkIaF9+ygCnkVUFMQ1lz7lcdOLpkr+hcukBADBi+eKMKHQ2eF61pOALDnS+eZYyrOoc0ukxO7ZWmGvfGSEsLD+z2nynplIXZB5ch/oBsHVFFBkfFepXEpju3L2mR23HVp2h97TRIEDByGVOTU9ZQmDwWckjoBrkN/ePD+Ar5mfQlycNCrrYf6+f82Q28zL6Cqr+srUKwAtOvQDqz+OTGmF2XJzo/nZ6SzrQfPqzjiGR/jlT/+Z7rsJ7/6C0fiioS9OmbwsqJEXrK21iBFt4VE0F7JRyzmt54F4j5AFOGKm/r5fSVIJt0mcNc40icm9SoRitanjIhviTCg+kYLPFdR2Zf7YSf1HTm0YqFli//2HNHUnhJtfQ6g7ky/zpOCId4FusSLS3qiZQWu1WX0tDWDrK9e/j/+bTeWA00ugaZA7i5agz+7DWAChW4cXi5zBtb7BJcqOGf5i397A==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: crossplane-system
    type: Opaque
