---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd-topic10
  namespace: flux-system
spec:
  chart:
    spec:
      chart: argo-cd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argocd
  install:
    createNamespace: true
  interval: 5m
  targetNamespace: argocd
  values:
    configs:
      cm:
        accounts.ops-project: login
        accounts.ops-infra: apiKey,login
        accounts.greader: login
        application.resourceTrackingMethod: annotation
        resource.exclusions: |
          - apiGroups:
            - "*"
            kinds:
            - ProviderConfigUsage
        resource.customizations: |
          "*.upbound.io/*":
            health.lua: |
              health_status = {
                status = "Progressing",
                message = "Provisioning ..."
              }

              local function contains (table, val)
                for i, v in ipairs(table) do
                  if v == val then
                    return true
                  end
                end
                return false
              end

              local has_no_status = {
                "ProviderConfig",
                "ProviderConfigUsage"
              }

              if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
                health_status.status = "Healthy"
                health_status.message = "Resource is up-to-date."
                return health_status
              end

              if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
                if obj.kind == "ProviderConfig" and obj.status.users ~= nil then
                  health_status.status = "Healthy"
                  health_status.message = "Resource is in use."
                  return health_status
                end
                return health_status
              end

              for i, condition in ipairs(obj.status.conditions) do
                if condition.type == "LastAsyncOperation" then
                  if condition.status == "False" then
                    health_status.status = "Degraded"
                    health_status.message = condition.message
                    return health_status
                  end
                end

                if condition.type == "Synced" then
                  if condition.status == "False" then
                    health_status.status = "Degraded"
                    health_status.message = condition.message
                    return health_status
                  end
                end

                if condition.type == "Ready" then
                  if condition.status == "True" then
                    health_status.status = "Healthy"
                    health_status.message = "Resource is up-to-date."
                    return health_status
                  end
                end
              end

              return health_status

          "*.crossplane.io/*":
            health.lua: |
              health_status = {
                status = "Progressing",
                message = "Provisioning ..."
              }

              local function contains (table, val)
                for i, v in ipairs(table) do
                  if v == val then
                    return true
                  end
                end
                return false
              end

              local has_no_status = {
                "Composition",
                "CompositionRevision",
                "DeploymentRuntimeConfig",
                "ControllerConfig",
                "ProviderConfig",
                "ProviderConfigUsage"
              }
              if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
                  health_status.status = "Healthy"
                  health_status.message = "Resource is up-to-date."
                return health_status
              end

              if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
                if obj.kind == "ProviderConfig" and obj.status.users ~= nil then
                  health_status.status = "Healthy"
                  health_status.message = "Resource is in use."
                  return health_status
                end
                return health_status
              end

              for i, condition in ipairs(obj.status.conditions) do
                if condition.type == "LastAsyncOperation" then
                  if condition.status == "False" then
                    health_status.status = "Degraded"
                    health_status.message = condition.message
                    return health_status
                  end
                end

                if condition.type == "Synced" then
                  if condition.status == "False" then
                    health_status.status = "Degraded"
                    health_status.message = condition.message
                    return health_status
                  end
                end

                if contains({"Ready", "Healthy", "Offered", "Established"}, condition.type) then
                  if condition.status == "True" then
                    health_status.status = "Healthy"
                    health_status.message = "Resource is up-to-date."
                    return health_status
                  end
                end
              end

              return health_status
      rbac:
        policy.csv: |
          p, greader, applications, get, */*, allow
          p, greader, projects, get, */*, allow
          p, role:opsproject, applications, *, */*, allow
          p, role:opsproject, repositories, *, */*, allow
          p, role:opsproject, logs, get, *, allow
          p, role:opsproject, clusters, *, */*, allow
          p, role:opsproject, exec, *, */*, allow
          p, role:opsproject, certificates, sync, */*, deny
          p, role:opsproject, gpgkeys, sync, */*, deny
          p, role:opsproject, accounts, sync, */*, deny
          p, role:opsproject, extensions, sync, */*, deny
          g, ops-project, role:opsproject
          g, ops-infra, role:admin
